### ISSUE TITLE
Error compiling when using Huzzah ESP8266 or Adafruit Feather M0 board

### ISSUE THREAD

**Issue by Loopbackconnector** [sparkfun/SparkFun_AS3935_Lightning_Detector#1]
When compiling Example1_BasicLightning and using either Huzzah  ESP8266 or Adafruit Feather M0 as the board type I get the following error:

Example1_BasicLightning:33:38: error: invalid conversion from 'int' to 'i2cAddress {aka SF_AS3935_I2C_ADDRESS}' [-fpermissive]
 SparkFun_AS3935 lightning(AS3935_ADDR);

**Comment by edspark** [comment]
Thanks for the issue, I'll get on this sometime in the next few days. Thanks for your patience!

**Comment by edspark** [comment]
In the future this is best filed underneath the library [repo](https://github.com/sparkfun/SparkFun_AS3935_Lightning_Detector_Arduino_Library), since it is a library issue. It was fixed with this commit: https://github.com/sparkfun/SparkFun_AS3935_Lightning_Detector_Arduino_Library/commit/271d5d1f4748dea87de263077b5cf0d9d4602a8f
